config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  root "articles#index"
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:category].blank?
      @articles = Article.all
    else
      @category_id = Category.find_by(name: params[:category]).id
      @articles = Article.where(category_id: @category_id).order("title ASC")
    end
  end

  def show
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  private

    def article_params
      params.require(:article).permit(:title, :content, :category_id)
    end

    def find_article
      @article = Article.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= simple_form_for(@article, html: { class: 'form-horizontal' }) do |f|
  = f.input :title
  = f.input :content
  = f.collection_select :category_id, Category.all.order("name ASC"), :id, :name, { prompt: "Choose a Category" }
  %br/
  = f.submit

app/views/articles/edit.html.haml
%h1 Edit Article
= render "form"
= link_to "Cancel", @article

app/views/articles/index.html.haml
- @articles.each do |article|
  %h2= link_to article.title, article
  %p
    Published at
    = article.created_at.strftime("%B %d, %Y")
  %p= truncate(article.content, length: 100)

app/views/articles/new.html.haml
%h1 New article
= render "form"
= link_to "Cancel", root_path

app/views/articles/show.html.haml
%h1= @article.title
%p= @article.content
%p= @article.category.name
%br/
.btn-group
  = link_to "Back", root_path, class: "btn btn-default"
  - if user_signed_in? && @article.user == current_user
    = link_to "Edit", edit_article_path, class: "btn btn-default"
    = link_to "Delete", @article, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title WikiTech
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default.navbar-fixed-top
    .container
      = link_to "WIKI TECH", root_path, class: "navbar-brand"
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to "New article", new_article_path
          %li= link_to "Sign out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign up", new_user_registration_path
          %li= link_to "Sign in", new_user_session_path

  %p.notice= notice
  %p.alert= alert

  .container
    .row
      .col-lg-8.col-md-8
        = yield
      .col-lg-4.col-md-4
        %ul.list-group
          %li= link_to "All", root_path, class: "list-group-item"
          - Category.all.order("name ASC").each do |category|
            %li= link_to category.name, articles_path(category: category.name), class: "list-group-item"